### PR TITLE
init automation engineer general kata, README

### PR DESCRIPTION
**Pull request by dbenedic-insight**
This PR adds the following:
* init the README
* Add general automation engineer kata

### CODE REVIEW

**Comment by mcknz-insight** [comment]
Looks good -- I like the options, since it covers hands-on as well as higher-level design.

Are we expecting their work to be available online somewhere? Or do we want them to build it locally and bring that in to show? If it's open we could probably mention that it's up to them how to display/present the work. Do we want to specify cloud, or is deploying locally an option?

Very minor suggestion -- lead with the task paragraph and perhaps give it a title/name (The Solution/The Application)? I feel like the instructions might read better if they are referring to something that's already been described.

**Comment by dbenedic-insight** [comment]
@mcknz-insight I integrated your feedback, please take another look.

**Review by mcknz-insight — CHANGES_REQUESTED** [review]
Just need to replace "the following task" in acceptance criteria with "the application" or similar. Also first sentence in Delivery should read "...with you or upload it..."

Otherwise looks good, will defer to Ray on approval.

**Comment by rayullery** [comment]
Looks great! Approved!

**Review by rayullery — APPROVED** [review]
👍

**Comment by dbenedic-insight** [comment]
I took the time to _actually_ proofread the kata 😆 

All requested changes have been made and I'm merging this PR.

Thanks @mcknz-insight and @rayullery!

**Pull request merged**
